Imported Upstream version 0.8

diff --git a/regress/r1test b/regress/r1test
--- a/regress/r1test
+++ b/regress/r1test
@@ -1,5 +1,27 @@
 #!/bin/sh
 # usage: r1test <testcasename>
+# test execution script, for running one test
+#
+#  This file is
+#    Copyright (C) 1998-2000 Ian Jackson <ian@davenant.greenend.org.uk>
+#
+#  It is part of adns, which is
+#    Copyright (C) 1997-2000 Ian Jackson <ian@davenant.greenend.org.uk>
+#    Copyright (C) 1999 Tony Finch <dot@dotat.at>
+#  
+#  This program is free software; you can redistribute it and/or modify
+#  it under the terms of the GNU General Public License as published by
+#  the Free Software Foundation; either version 2, or (at your option)
+#  any later version.
+#  
+#  This program is distributed in the hope that it will be useful,
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#  GNU General Public License for more details.
+#  
+#  You should have received a copy of the GNU General Public License
+#  along with this program; if not, write to the Free Software Foundation,
+#  Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA. 
 
 set -e
 mrc=1
@@ -42,13 +64,20 @@ do
 	then
 		:
 	else
-		failed=true
+		failwhy="$failwhy WRONG OUTPUT"
 	fi
 done
 
-if $failed
+cat >"$ocase.leftover"
+if egrep . /dev/null "$ocase.leftover"
 then
-	echo >&2 "FAILED $case - WRONG OUTPUT - lines of syscall remaining `wc -l`"
+	failwhy="$failwhy EXITED EARLY"
+fi
+
+if [ "x$failwhy" != x ]
+then
+	scremain="`wc -l <\"$ocase.leftover\"`"
+	echo >&2 "FAILED $case -$failwhy - lines of syscall remaining $scremain"
 	mrc=2
 	exit
 fi
